on:
  pull_request:
  label:

name: Changelog

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Check that changelog updated
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: CHANGELOG.md
          skipLabels: "skip-changelog"
          missingUpdateErrorMessage: "Please add a changelog entry in the CHANGELOG.md file."

