name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - thumbv7em-none-eabihf
          - thumbv6m-none-eabi
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Toolchain and tools
        run: |
          rustup update stable
          rustup default stable
          cargo install --locked --version 1.12.0 cargo-all-features

      - name: cargo-fmt
        run: cargo fmt --check --verbose

      - name: cargo-clippy
        run:  cargo clippy -p usbd-storage --target ${{matrix.target}} --all-features --verbose

      - name: cargo-test
        run: cargo test -p usbd-storage --all-features

      - name: cargo-build
        run: cargo build -p usbd-storage --target ${{matrix.target}} --verbose

      - name: cargo-build-all-features
        run: cargo all-features build -p usbd-storage --target ${{matrix.target}} --verbose

      - name: cargo-build examples/stm32
        if: ${{matrix.target == 'thumbv7em-none-eabihf'}}
        run: |
          cargo build -p stm32 --target ${{matrix.target}} --verbose
          cargo clippy -p stm32 --target ${{matrix.target}} --all-features --verbose

      - name: cargo-build examples/rp2040
        if: ${{matrix.target == 'thumbv6m-none-eabi'}}
        run: |
          cargo build -p rp2040 --target ${{matrix.target}} --verbose
          cargo clippy -p rp2040 --target ${{matrix.target}} --all-features --verbose

